### PR TITLE
Issue 2 and 3: Save image link and show index

### PR DESCRIPTION
**Pull request by jeremykirc**

### CODE REVIEW

**Review by zju2 — APPROVED** [review]
LGTM

**Review by aman-singh — APPROVED** [review]
Looks good!

**Comment by jeremykirc** [comment]
[Issue 2: Save Image Link](https://trello.com/c/hhjsHkTe/997-issue-2-save-image-link)

**Comment by jeremykirc** [comment]
[Issue 3: Image Index](https://trello.com/c/l6xazsUg/995-issue-3-image-index)

**Pull request merged**
